[Home](../../README.md)

### Data Wrangling

This is a demonstration of data wrangling using [Pandas](https://pandas.pydata.org/) the library for data analysis and manipulation.

This Jupyter Notepad demonstrates different processes you can apply to your data to prepare it for feature engineering and model training. For this demonstration we will wrangle the diabetes data set you previewed in the last Jupyter Notebook.

> [!Note]
> None of these processes are destructive to the source CSV as long as you save the modified data to a new CSV.

#### Load the required dependencies

In [1]:
# Import frameworks
import pandas as pd

####  Store the data as a local variable

The data frame is a Pandas object that structures your tabular data into an appropriate format. It loads the complete data in memory so it is now ready for preprocessing.

In [2]:
data_frame = pd.read_csv("2.1.2.minecraft_100x100.csv")

#### Dealing with null values

Null values during data analysis can cause runtime errors and unexpected results. It is important to identify null values and deal with them appropriately before training a model.

The `isnull().sum()` method call returns the null values in any column.

In [3]:
pd.set_option("display.max_rows", None)
data_frame.isnull().sum()

chunk_x                                       0
chunk_z                                       0
dominant_biome                                0
minecraft:acacia_leaves                       0
minecraft:acacia_log                          0
minecraft:air                                 0
minecraft:amethyst_block                      0
minecraft:amethyst_cluster                    0
minecraft:andesite                            0
minecraft:azalea                              0
minecraft:azalea_leaves                       0
minecraft:azure_bluet                         0
minecraft:barrel                              0
minecraft:bedrock                             0
minecraft:bee_nest                            0
minecraft:beetroots                           0
minecraft:bell                                0
minecraft:big_dripleaf                        0
minecraft:big_dripleaf_stem                   0
minecraft:birch_fence                         0
minecraft:birch_leaves                        0
minecraft:birch_log                           0
minecraft:birch_planks                        0
minecraft:birch_slab                          0
minecraft:birch_stairs                        0
minecraft:black_bed                           0
minecraft:black_stained_glass                 0
minecraft:blast_furnace                       0
minecraft:blue_bed                            0
minecraft:blue_orchid                         0
minecraft:blue_terracotta                     0
minecraft:bone_block                          0
minecraft:brick_slab                          0
minecraft:brick_stairs                        0
minecraft:bricks                              0
minecraft:brown_bed                           0
minecraft:brown_mushroom                      0
minecraft:brown_mushroom_block                0
minecraft:budding_amethyst                    0
minecraft:bush                                0
minecraft:cactus                              0
minecraft:calcite                             0
minecraft:campfire                            0
minecraft:candle                              0
minecraft:carrots                             0
minecraft:cartography_table                   0
minecraft:cauldron                            0
minecraft:cave_air                            0
minecraft:cave_vines                          0
minecraft:cave_vines_plant                    0
minecraft:chest                               0
minecraft:chiseled_sandstone                  0
minecraft:chiseled_stone_bricks               0
minecraft:chiseled_tuff                       0
minecraft:chiseled_tuff_bricks                0
minecraft:clay                                0
minecraft:coal_block                          0
minecraft:coal_ore                            0
minecraft:coarse_dirt                         0
minecraft:cobbled_deepslate                   0
minecraft:cobblestone                         0
minecraft:cobblestone_stairs                  0
minecraft:cobblestone_wall                    0
minecraft:cobweb                              0
minecraft:composter                           0
minecraft:copper_block                        0
minecraft:copper_ore                          0
minecraft:cornflower                          0
minecraft:cracked_stone_bricks                0
minecraft:crafting_table                      0
minecraft:crying_obsidian                     0
minecraft:cyan_bed                            0
minecraft:cyan_terracotta                     0
minecraft:dandelion                           0
minecraft:dark_oak_door                       0
minecraft:dark_oak_fence                      0
minecraft:dark_oak_leaves                     0
minecraft:dark_oak_log                        0
minecraft:dark_oak_planks                     0
minecraft:dark_oak_slab                       0
minecraft:dark_oak_stairs                     0
minecraft:dark_oak_trapdoor                   0
minecraft:dark_prismarine                     0
minecraft:dead_bush                           0
minecraft:decorated_pot                       0
minecraft:deepslate                           0
minecraft:deepslate_coal_ore                  0
minecraft:deepslate_copper_ore                0
minecraft:deepslate_diamond_ore               0
minecraft:deepslate_emerald_ore               0
minecraft:deepslate_gold_ore                  0
minecraft:deepslate_iron_ore                  0
minecraft:deepslate_lapis_ore                 0
minecraft:deepslate_redstone_ore              0
minecraft:diamond_ore                         0
minecraft:diorite                             0
minecraft:dirt                                0
minecraft:dirt_path                           0
minecraft:dispenser                           0
minecraft:dripstone_block                     0
minecraft:emerald_ore                         0
minecraft:farmland                            0
minecraft:fern                                0
minecraft:firefly_bush                        0
minecraft:flower_pot                          0
minecraft:flowering_azalea                    0
minecraft:flowering_azalea_leaves             0
minecraft:furnace                             0
minecraft:glass_pane                          0
minecraft:glow_lichen                         0
minecraft:gold_block                          0
minecraft:gold_ore                            0
minecraft:granite                             0
minecraft:grass_block                         0
minecraft:gravel                              0
minecraft:gray_bed                            0
minecraft:gray_terracotta                     0
minecraft:green_carpet                        0
minecraft:grindstone                          0
minecraft:hanging_roots                       0
minecraft:hay_block                           0
minecraft:hopper                              0
minecraft:infested_deepslate                  0
minecraft:infested_stone                      0
minecraft:iron_bars                           0
minecraft:iron_chain                          0
minecraft:iron_ore                            0
minecraft:jungle_fence                        0
minecraft:jungle_planks                       0
minecraft:jungle_slab                         0
minecraft:jungle_stairs                       0
minecraft:kelp                                0
minecraft:kelp_plant                          0
minecraft:ladder                              0
minecraft:lapis_ore                           0
minecraft:large_amethyst_bud                  0
minecraft:large_fern                          0
minecraft:lava                                0
minecraft:leaf_litter                         0
minecraft:light_blue_bed                      0
minecraft:light_blue_glazed_terracotta        0
minecraft:light_gray_bed                      0
minecraft:light_gray_glazed_terracotta        0
minecraft:light_gray_stained_glass            0
minecraft:light_gray_terracotta               0
minecraft:lilac                               0
minecraft:lily_of_the_valley                  0
minecraft:lily_pad                            0
minecraft:lime_bed                            0
minecraft:loom                                0
minecraft:magenta_bed                         0
minecraft:magma_block                         0
minecraft:mangrove_leaves                     0
minecraft:mangrove_log                        0
minecraft:mangrove_roots                      0
minecraft:mangrove_wood                       0
minecraft:medium_amethyst_bud                 0
minecraft:moss_block                          0
minecraft:moss_carpet                         0
minecraft:mossy_cobblestone                   0
minecraft:mossy_stone_brick_slab              0
minecraft:mossy_stone_brick_stairs            0
minecraft:mossy_stone_bricks                  0
minecraft:mud                                 0
minecraft:mud_brick_slab                      0
minecraft:mud_brick_stairs                    0
minecraft:mud_brick_wall                      0
minecraft:mud_bricks                          0
minecraft:muddy_mangrove_roots                0
minecraft:mushroom_stem                       0
minecraft:netherrack                          0
minecraft:oak_button                          0
minecraft:oak_door                            0
minecraft:oak_fence                           0
minecraft:oak_fence_gate                      0
minecraft:oak_leaves                          0
minecraft:oak_log                             0
minecraft:oak_planks                          0
minecraft:oak_pressure_plate                  0
minecraft:oak_slab                            0
minecraft:oak_stairs                          0
minecraft:oak_trapdoor                        0
minecraft:obsidian                            0
minecraft:orange_bed                          0
minecraft:orange_glazed_terracotta            0
minecraft:orange_terracotta                   0
minecraft:oxeye_daisy                         0
minecraft:oxidized_copper_trapdoor            0
minecraft:oxidized_cut_copper                 0
minecraft:packed_ice                          0
minecraft:packed_mud                          0
minecraft:peony                               0
minecraft:pink_bed                            0
minecraft:podzol                              0
minecraft:pointed_dripstone                   0
minecraft:polished_andesite                   0
minecraft:polished_granite                    0
minecraft:polished_tuff                       0
minecraft:polished_tuff_slab                  0
minecraft:poppy                               0
minecraft:potatoes                            0
minecraft:potted_dead_bush                    0
minecraft:powder_snow                         0
minecraft:prismarine                          0
minecraft:prismarine_bricks                   0
minecraft:pumpkin                             0
minecraft:purple_bed                          0
minecraft:rail                                0
minecraft:raw_copper_block                    0
minecraft:raw_iron_block                      0
minecraft:red_bed                             0
minecraft:red_candle                          0
minecraft:red_concrete                        0
minecraft:red_glazed_terracotta               0
minecraft:red_mushroom                        0
minecraft:red_mushroom_block                  0
minecraft:red_terracotta                      0
minecraft:redstone_ore                        0
minecraft:rooted_dirt                         0
minecraft:rose_bush                           0
minecraft:sand                                0
minecraft:sandstone                           0
minecraft:sculk                               0
minecraft:sculk_catalyst                      0
minecraft:sculk_sensor                        0
minecraft:sculk_shrieker                      0
minecraft:sculk_vein                          0
minecraft:sea_lantern                         0
minecraft:seagrass                            0
minecraft:short_grass                         0
minecraft:small_amethyst_bud                  0
minecraft:small_dripleaf                      0
minecraft:smithing_table                      0
minecraft:smooth_basalt                       0
minecraft:smooth_stone                        0
minecraft:smooth_stone_slab                   0
minecraft:snow                                0
minecraft:spawner                             0
minecraft:spore_blossom                       0
minecraft:spruce_door                         0
minecraft:spruce_fence                        0
minecraft:spruce_leaves                       0
minecraft:spruce_log                          0
minecraft:spruce_planks                       0
minecraft:spruce_slab                         0
minecraft:spruce_stairs                       0
minecraft:spruce_trapdoor                     0
minecraft:stone                               0
minecraft:stone_brick_slab                    0
minecraft:stone_brick_stairs                  0
minecraft:stone_bricks                        0
minecraft:stone_button                        0
minecraft:stone_slab                          0
minecraft:stripped_oak_log                    0
minecraft:stripped_oak_wood                   0
minecraft:sugar_cane                          0
minecraft:suspicious_gravel                   0
minecraft:sweet_berry_bush                    0
minecraft:tall_grass                          0
minecraft:tall_seagrass                       0
minecraft:torch                               0
minecraft:trial_spawner                       0
minecraft:tripwire                            0
minecraft:tripwire_hook                       0
minecraft:tuff                                0
minecraft:tuff_bricks                         0
minecraft:vault                               0
minecraft:vine                                0
minecraft:wall_torch                          0
minecraft:water                               0
minecraft:waxed_chiseled_copper               0
minecraft:waxed_copper_block                  0
minecraft:waxed_copper_bulb                   0
minecraft:waxed_copper_door                   0
minecraft:waxed_copper_grate                  0
minecraft:waxed_cut_copper                    0
minecraft:waxed_cut_copper_slab               0
minecraft:waxed_cut_copper_stairs             0
minecraft:waxed_exposed_copper_bulb           0
minecraft:waxed_oxidized_chiseled_copper      0
minecraft:waxed_oxidized_copper               0
minecraft:waxed_oxidized_copper_bulb          0
minecraft:waxed_oxidized_copper_door          0
minecraft:waxed_oxidized_copper_grate         0
minecraft:waxed_oxidized_copper_trapdoor      0
minecraft:waxed_oxidized_cut_copper           0
minecraft:waxed_oxidized_cut_copper_slab      0
minecraft:waxed_oxidized_cut_copper_stairs    0
minecraft:waxed_weathered_copper_bulb         0
minecraft:wet_sponge                          0
minecraft:wheat                               0
minecraft:white_bed                           0
minecraft:white_carpet                        0
minecraft:white_concrete                      0
minecraft:white_stained_glass                 0
minecraft:white_terracotta                    0
minecraft:white_wool                          0
minecraft:wildflowers                         0
minecraft:yellow_bed                          0
minecraft:yellow_carpet                       0
minecraft:yellow_glazed_terracotta            0
minecraft:yellow_wool                         0
dtype: int64

If you have null data there are many ways to deal with the empty/null values. These are the two most common approaches.
1. Remove any row with a null value with a `dropna()` method call.
2. Replace missing values with another value with a `fillna()` method call. Generally, we use mean value for numerical columns because it may cause minimal changes in your mathematical analysis while maintaining the original size of the data.

Students should reflect why this example removes the null 'SEX' but replacing the mean 'Target'?

In [4]:
# No Null values

# data_frame = data_frame.dropna(subset=['SEX'])
# data_frame.isnull().sum()

In [5]:
# No Null values

# data_frame['Target'] = data_frame['Target'].fillna(data_frame['Target'].mean())
# data_frame.isnull().sum()

#### Replace data

In order to improve the readibility and usability of my targets, I am going to remove the common prefix from every value.

In [6]:
data_frame['dominant_biome'] = data_frame['dominant_biome'].apply(lambda x: x.replace('minecraft:', ''))
data_frame['dominant_biome'].head()

0    cold_ocean
1    cold_ocean
2    cold_ocean
3    cold_ocean
4    cold_ocean
Name: dominant_biome, dtype: str

Then, I'll do the same with my features (to improve load time or readability)

In [7]:
data_frame.columns = data_frame.columns.str.replace("minecraft:", "", regex=False)
data_frame.head()

,chunk_x,chunk_z,dominant_biome,acacia_leaves,acacia_log,air,amethyst_block,amethyst_cluster,andesite,azalea,...,white_carpet,white_concrete,white_stained_glass,white_terracotta,white_wool,wildflowers,yellow_bed,yellow_carpet,yellow_glazed_terracotta,yellow_wool
0,0,0,cold_ocean,0,0,66914,0,0,1086,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,cold_ocean,0,0,67433,0,0,1274,0,...,0,0,0,0,0,0,0,0,0,0
2,1,1,cold_ocean,0,0,67102,0,0,873,1,...,0,0,0,0,0,0,0,0,0,0
3,0,1,cold_ocean,0,0,67086,0,0,1174,10,...,0,0,0,0,0,0,0,0,0,0
4,-1,1,cold_ocean,0,0,66035,0,0,1003,0,...,0,0,0,0,0,0,0,0,0,0

#### Drop/combine unecessary targets

(for the purpose of simplifying the algorithm and preventing overfitting)

In [8]:
data_frame['dominant_biome'].unique()

<StringArray>
[              'cold_ocean',                    'beach',
                    'river',          'deep_cold_ocean',
                    'taiga',                   'forest',
                    'ocean',               'deep_ocean',
                   'plains',             'birch_forest',
              'dark_forest',  'old_growth_birch_forest',
 'windswept_gravelly_hills',    'old_growth_pine_taiga',
        'windswept_savanna',  'old_growth_spruce_taiga',
                    'swamp',                   'meadow']
Length: 18, dtype: str

In [9]:
data_frame['dominant_biome'] = data_frame['dominant_biome'].apply(
    lambda biome: 'ocean' if 'ocean' in biome else biome
)
data_frame["dominant_biome"] = data_frame["dominant_biome"].apply(
    lambda biome: "taiga" if "taiga" in biome else biome
)
data_frame["dominant_biome"] = data_frame["dominant_biome"].apply(
    lambda biome: "birch_forest" if "birch_forest" in biome else biome
)
data_frame["dominant_biome"].unique()

<StringArray>
[                   'ocean',                    'beach',
                    'river',                    'taiga',
                   'forest',                   'plains',
             'birch_forest',              'dark_forest',
 'windswept_gravelly_hills',        'windswept_savanna',
                    'swamp',                   'meadow']
Length: 12, dtype: str

#### Drop unecessary features

Many of my features are not necessary for the algorithms prediction, either being very rare (only in one or two chunks), or are in every single chunk no matter what (e.g. bedrock).

In [10]:
df = pd.read_csv("2.1.2.minecraft_100x100.csv")
zero_counts = (df == 0).sum(axis=0)
zero_summary = pd.DataFrame({"Column": df.columns, "Zero Count": zero_counts.values})
zero_summary = zero_summary.sort_values("Zero Count", ascending=True)
print(zero_summary.to_string(index=False))

                                    Column  Zero Count
                            dominant_biome           0
                       minecraft:deepslate           0
                          minecraft:gravel           0
                           minecraft:stone           0
                         minecraft:bedrock           0
                             minecraft:air           0
                      minecraft:copper_ore           3
                         minecraft:diorite           3
                            minecraft:tuff           3
                        minecraft:andesite           4
                         minecraft:granite           4
          minecraft:deepslate_redstone_ore           6
                        minecraft:iron_ore           7
           minecraft:deepslate_diamond_ore          23
              minecraft:deepslate_iron_ore          24
                            minecraft:dirt          29
              minecraft:deepslate_gold_ore          58
                                   chunk_x         101
                                   chunk_z         101
                        minecraft:coal_ore         153
             minecraft:deepslate_lapis_ore         180
                       minecraft:lapis_ore         476
                           minecraft:water        1670
                     minecraft:glow_lichen        2539
                     minecraft:short_grass        2744
            minecraft:deepslate_copper_ore        3055
                     minecraft:grass_block        3452
                        minecraft:gold_ore        4243
                            minecraft:clay        4630
                    minecraft:redstone_ore        4903
                            minecraft:lava        6096
                        minecraft:seagrass        6351
                            minecraft:sand        6453
                   minecraft:tall_seagrass        6462
                      minecraft:moss_block        6910
                     minecraft:leaf_litter        7141
                      minecraft:oak_leaves        7246
                      minecraft:cave_vines        7288
                    minecraft:birch_leaves        7379
                         minecraft:oak_log        7388
                minecraft:cave_vines_plant        7459
                      minecraft:tall_grass        7565
                     minecraft:moss_carpet        7794
                       minecraft:birch_log        7806
                            minecraft:vine        8001
                        minecraft:cave_air        8042
                          minecraft:azalea        8187
                minecraft:flowering_azalea        8469
                     minecraft:magma_block        8492
                    minecraft:big_dripleaf        8781
                     minecraft:diamond_ore        8791
                            minecraft:kelp        8808
                      minecraft:kelp_plant        8812
                      minecraft:oak_planks        8849
                       minecraft:oak_fence        8969
                   minecraft:smooth_basalt        8991
                 minecraft:dark_oak_leaves        9016
                          minecraft:cobweb        9062
              minecraft:deepslate_coal_ore        9063
                    minecraft:dark_oak_log        9074
               minecraft:big_dripleaf_stem        9082
                         minecraft:calcite        9154
                   minecraft:spruce_leaves        9179
                     minecraft:wildflowers        9199
                      minecraft:spruce_log        9239
                            minecraft:bush        9277
                            minecraft:fern        9292
                  minecraft:amethyst_block        9294
                            minecraft:rail        9311
                minecraft:budding_amethyst        9366
               minecraft:mossy_cobblestone        9380
                  minecraft:small_dripleaf        9387
                   minecraft:spore_blossom        9445
                       minecraft:sandstone        9515
                  minecraft:brown_mushroom        9654
                  minecraft:raw_iron_block        9665
                     minecraft:cobblestone        9711
                minecraft:raw_copper_block        9722
                 minecraft:dripstone_block        9732
               minecraft:pointed_dripstone        9757
                       minecraft:dandelion        9785
              minecraft:red_mushroom_block        9817
                          minecraft:podzol        9824
                   minecraft:mushroom_stem        9838
              minecraft:small_amethyst_bud        9839
                minecraft:amethyst_cluster        9849
                      minecraft:large_fern        9852
             minecraft:medium_amethyst_bud        9856
                           minecraft:chest        9859
                      minecraft:wall_torch        9860
              minecraft:large_amethyst_bud        9872
                     minecraft:tuff_bricks        9878
                         minecraft:spawner        9895
              minecraft:waxed_copper_block        9898
            minecraft:chiseled_tuff_bricks        9898
                           minecraft:poppy        9911
                   minecraft:polished_tuff        9915
               minecraft:waxed_copper_bulb        9919
           minecraft:waxed_oxidized_copper        9923
       minecraft:waxed_oxidized_cut_copper        9955
minecraft:waxed_oxidized_cut_copper_stairs        9962
       minecraft:waxed_exposed_copper_bulb        9963
     minecraft:waxed_weathered_copper_bulb        9965
           minecraft:waxed_chiseled_copper        9985
                     minecraft:coarse_dirt        9991
            minecraft:brown_mushroom_block       10008
              minecraft:waxed_copper_grate       10010
                   minecraft:chiseled_tuff       10028
                      minecraft:iron_chain       10031
              minecraft:infested_deepslate       10044
      minecraft:waxed_oxidized_copper_bulb       10046
                  minecraft:infested_stone       10052
                       minecraft:dead_bush       10053
                     minecraft:oxeye_daisy       10067
                     minecraft:emerald_ore       10072
                      minecraft:cornflower       10077
                           minecraft:vault       10078
                     minecraft:azure_bluet       10078
                    minecraft:firefly_bush       10079
     minecraft:waxed_oxidized_copper_grate       10083
                          minecraft:barrel       10087
                        minecraft:lily_pad       10087
                      minecraft:sculk_vein       10093
           minecraft:waxed_cut_copper_slab       10093
                           minecraft:sculk       10095
                minecraft:waxed_cut_copper       10103
                      minecraft:sugar_cane       10105
                    minecraft:red_mushroom       10106
                       minecraft:dispenser       10107
                   minecraft:trial_spawner       10111
                      minecraft:oak_button       10112
                          minecraft:hopper       10121
                      minecraft:red_candle       10131
                   minecraft:decorated_pot       10132
              minecraft:polished_tuff_slab       10134
           minecraft:red_glazed_terracotta       10135
                          minecraft:ladder       10141
                      minecraft:bone_block       10144
                       minecraft:dirt_path       10149
                          minecraft:candle       10149
                           minecraft:lilac       10154
                   minecraft:azalea_leaves       10154
                     minecraft:rooted_dirt       10155
              minecraft:lily_of_the_valley       10155
      minecraft:waxed_oxidized_copper_door       10155
         minecraft:flowering_azalea_leaves       10156
                       minecraft:rose_bush       10158
                           minecraft:peony       10158
             minecraft:oxidized_cut_copper       10160
                minecraft:potted_dead_bush       10160
  minecraft:waxed_oxidized_copper_trapdoor       10162
                minecraft:sweet_berry_bush       10164
                      minecraft:flower_pot       10165
                      minecraft:oak_stairs       10169
                    minecraft:sculk_sensor       10169
                   minecraft:hanging_roots       10170
               minecraft:cobbled_deepslate       10172
                        minecraft:bee_nest       10174
                      minecraft:netherrack       10177
         minecraft:waxed_cut_copper_stairs       10179
                         minecraft:pumpkin       10179
               minecraft:suspicious_gravel       10179
                    minecraft:stone_bricks       10179
                      minecraft:packed_ice       10180
                  minecraft:sculk_catalyst       10180
                      minecraft:glass_pane       10181
            minecraft:cracked_stone_bricks       10183
                minecraft:white_terracotta       10184
                      minecraft:prismarine       10185
               minecraft:prismarine_bricks       10185
                     minecraft:sea_lantern       10185
        minecraft:light_gray_stained_glass       10185
                     minecraft:powder_snow       10187
                 minecraft:dark_prismarine       10187
              minecraft:oak_pressure_plate       10187
                        minecraft:oak_door       10187
                   minecraft:spruce_stairs       10189
             minecraft:white_stained_glass       10189
                            minecraft:snow       10189
                   minecraft:spruce_planks       10189
              minecraft:cobblestone_stairs       10190
                    minecraft:spruce_fence       10190
  minecraft:waxed_oxidized_cut_copper_slab       10190
                      minecraft:mud_bricks       10190
              minecraft:mossy_stone_bricks       10191
             minecraft:black_stained_glass       10191
                        minecraft:oak_slab       10191
                      minecraft:yellow_bed       10191
                    minecraft:red_concrete       10192
           minecraft:deepslate_emerald_ore       10192
  minecraft:waxed_oxidized_chiseled_copper       10192
                  minecraft:red_terracotta       10192
                      minecraft:purple_bed       10192
              minecraft:stone_brick_stairs       10193
                      minecraft:packed_mud       10193
                  minecraft:white_concrete       10194
                       minecraft:white_bed       10194
                  minecraft:sculk_shrieker       10194
                 minecraft:cyan_terracotta       10194
                 minecraft:dark_oak_stairs       10194
                minecraft:stripped_oak_log       10194
               minecraft:waxed_copper_door       10194
                  minecraft:mud_brick_slab       10195
                  minecraft:light_gray_bed       10195
                minecraft:mud_brick_stairs       10195
                     minecraft:spruce_slab       10195
                minecraft:stone_brick_slab       10195
                        minecraft:obsidian       10195
                          minecraft:bricks       10195
              minecraft:chiseled_sandstone       10195
                 minecraft:blue_terracotta       10195
          minecraft:mossy_stone_brick_slab       10196
                 minecraft:dark_oak_planks       10196
                        minecraft:farmland       10196
                      minecraft:gold_block       10196
                    minecraft:brick_stairs       10196
                         minecraft:carrots       10196
                      minecraft:grindstone       10197
        minecraft:oxidized_copper_trapdoor       10197
                    minecraft:oak_trapdoor       10197
                        minecraft:potatoes       10197
               minecraft:orange_terracotta       10197
                             minecraft:mud       10197
                      minecraft:brick_slab       10197
                  minecraft:light_blue_bed       10197
               minecraft:dark_oak_trapdoor       10197
                    minecraft:stone_button       10197
                 minecraft:crying_obsidian       10197
                   minecraft:acacia_leaves       10197
                  minecraft:crafting_table       10197
                    minecraft:copper_block       10197
                           minecraft:wheat       10197
                       minecraft:brown_bed       10197
                     minecraft:blue_orchid       10197
                 minecraft:spruce_trapdoor       10198
                    minecraft:birch_planks       10198
                            minecraft:loom       10198
               minecraft:smooth_stone_slab       10198
                        minecraft:gray_bed       10198
                      minecraft:orange_bed       10198
        minecraft:mossy_stone_brick_stairs       10198
                        minecraft:lime_bed       10198
           minecraft:light_gray_terracotta       10198
                       minecraft:composter       10198
        minecraft:orange_glazed_terracotta       10198
                        minecraft:blue_bed       10198
                       minecraft:black_bed       10198
                   minecraft:tripwire_hook       10198
                      minecraft:acacia_log       10198
                       minecraft:beetroots       10198
                        minecraft:tripwire       10198
            minecraft:muddy_mangrove_roots       10199
                  minecraft:oak_fence_gate       10199
                  minecraft:mud_brick_wall       10199
                        minecraft:pink_bed       10199
               minecraft:polished_andesite       10199
                      minecraft:white_wool       10199
                   minecraft:blast_furnace       10199
                    minecraft:birch_stairs       10199
                         minecraft:furnace       10199
                       minecraft:hay_block       10199
                           minecraft:torch       10199
    minecraft:light_gray_glazed_terracotta       10199
    minecraft:light_blue_glazed_terracotta       10199
                    minecraft:jungle_fence       10199
                       minecraft:iron_bars       10199
                    minecraft:mangrove_log       10199
                 minecraft:mangrove_leaves       10199
                   minecraft:mangrove_wood       10199
                  minecraft:mangrove_roots       10199
                     minecraft:spruce_door       10199
           minecraft:chiseled_stone_bricks       10199
                            minecraft:bell       10199
                minecraft:cobblestone_wall       10199
                      minecraft:coal_block       10199
                        minecraft:campfire       10199
                     minecraft:birch_fence       10199
                          minecraft:cactus       10199
                     minecraft:yellow_wool       10199
        minecraft:yellow_glazed_terracotta       10200
                   minecraft:yellow_carpet       10200
                    minecraft:white_carpet       10200
                      minecraft:wet_sponge       10200
                      minecraft:birch_slab       10200
               minecraft:stripped_oak_wood       10200
                      minecraft:stone_slab       10200
                    minecraft:smooth_stone       10200
                  minecraft:smithing_table       10200
                         minecraft:red_bed       10200
                minecraft:polished_granite       10200
                     minecraft:magenta_bed       10200
                   minecraft:jungle_stairs       10200
                     minecraft:jungle_slab       10200
                   minecraft:jungle_planks       10200
                    minecraft:green_carpet       10200
                 minecraft:gray_terracotta       10200
                   minecraft:dark_oak_slab       10200
                  minecraft:dark_oak_fence       10200
                   minecraft:dark_oak_door       10200
                        minecraft:cyan_bed       10200
                        minecraft:cauldron       10200
               minecraft:cartography_table       10200

I have attempted to filter features by the amount of 0 values to determine their importance, but I have decided that I will need to manually select which features to keep based on my domain knowledge.

In [11]:
# chunk_x, chunk_z, dominant_biome, air, dirt, water, short_grass, grass_block, lava, sand, tall_seagrass, oak_leaves, birch_leaves, oak_log, tall_grass, birch_log, kelp, kelp_plant, oak_planks, oak_fence, dark_oak_log, dark_oak_leaves, spruce_leaves, spruce_log, bush, sandstone, brown_mushroom, dandelion, podzol, red_mushroom_block, mushroom_stem, poppy, coarse_dirt, oxeye_daisy, cornflower, azure_bluet, emerald_ore, lily_pad, barrel, sugar_cane, red_mushroom, lilac, lily_of_the_valley, rose_bush, peony, sweet_berry_bush, bee_nest, pumpkin, snow, acacia_leaves, acacia_log, blue_orchid

columns_to_keep = [
    "chunk_x",
    "chunk_z",
    "dominant_biome",
    "air",
    "dirt",
    "water",
    "short_grass",
    "grass_block",
    "lava",
    "sand",
    "tall_seagrass",
    "oak_leaves",
    "birch_leaves",
    "oak_log",
    "tall_grass",
    "birch_log",
    "kelp",
    "kelp_plant",
    "oak_planks",
    "oak_fence",
    "dark_oak_log",
    "dark_oak_leaves",
    "spruce_leaves",
    "spruce_log",
    "bush",
    "sandstone",
    "brown_mushroom",
    "dandelion",
    "podzol",
    "red_mushroom_block",
    "mushroom_stem",
    "poppy",
    "coarse_dirt",
    "oxeye_daisy",
    "cornflower",
    "azure_bluet",
    "emerald_ore",
    "lily_pad",
    "barrel",
    "sugar_cane",
    "red_mushroom",
    "lilac",
    "lily_of_the_valley",
    "rose_bush",
    "peony",
    "sweet_berry_bush",
    "bee_nest",
    "pumpkin",
    "snow",
    "acacia_leaves",
    "acacia_log",
    "blue_orchid",
]

data_frame = data_frame[columns_to_keep]
data_frame.head()

,chunk_x,chunk_z,dominant_biome,air,dirt,water,short_grass,grass_block,lava,sand,...,lily_of_the_valley,rose_bush,peony,sweet_berry_bush,bee_nest,pumpkin,snow,acacia_leaves,acacia_log,blue_orchid
0,0,0,ocean,66914,309,3509,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,ocean,67433,275,4174,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,1,ocean,67102,407,4202,6,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,1,ocean,67086,121,3825,34,0,0,96,...,0,0,0,0,0,0,0,0,0,0
4,-1,1,ocean,66035,400,3889,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0

#### Remove outliers

Outliers can skew your analysis on numerical columns, and it is important to remove them. We can use the 25th and 75th quartile on numerical data, to get the inter-quartile range. This allows us to estimate an acceptable range, and we can then filter out any values outside this range. Mathematically, outliers are values occurring outside 1.5 times the interquartile range (IQR) from the first quartile (Q1) or third quartile (Q3).

In [12]:
# get the inter-quartile range on all biomes blocks
# Outliers are negligible and may have to be adressed after cutting down features

blocks = [
    'air', 'water'
]
for block in blocks:
    print(data_frame[block].describe())
    Q1 = data_frame[block].quantile(0.10)
    Q3 = data_frame[block].quantile(0.90)
    IQR = Q3 - Q1
    print(f'Outliers are a {block} count above {Q3 + IQR} or below {Q1 - IQR}')

count    10201.000000
mean     66242.230075
std       3615.903324
min      49720.000000
25%      65083.000000
50%      66129.000000
75%      67392.000000
max      89631.000000
Name: air, dtype: float64
Outliers are a air count above 76104.0 or below 56589.0
count    10201.000000
mean      1811.044505
std       2248.280411
min          0.000000
25%         26.000000
50%        717.000000
75%       3223.000000
max      15724.000000
Name: water, dtype: float64
Outliers are a water count above 10104.0 or below -5052.0

In [13]:
# Outliers are not being filtered as they are negligible

# data_frame = data_frame[(data_frame['BP'] >= Q1 - 1.5 * IQR) & (data_frame['BP'] <= Q3 + 1.5 * IQR)]
# print(data_frame['BP'].describe())

#### Scaling features to a common range

Scaling the features makes it easier for machine learning algorithms to find the optimal solution, as the different scales of the features do not influence them.

In [14]:
# All features are on the exact same scale already, no need for feature scaling

# scale_feature = 'BP'
# #the minimum value with space for outliers
# MIN_BP = 55
# #the maximum value with space for outliers
# MAX_BP = 140
# #scale features
# data_frame[scale_feature] = [(X - MIN_BP) / (MAX_BP - MIN_BP) for X in data_frame[scale_feature]]
# data_frame.describe()

> [!important]
> You need to save the calculations for each dataset you scale for scaling new values for prediction. Use [2.1.2.data.records.md](2.1.2.data.records.md) to record this information.

#### Save the wrangled data to CSV

In [15]:
data_frame.to_csv('../2.2.Feature_Engineering/2.2.1.wrangled_data.csv', index=False)